# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Project/Vivado/lab0/OExo01-Element/OExo01-Element.srcs/sources_1/ip/ROM_D_1/ROM_D.xci
# IP: The module: 'ROM_D' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Project/Vivado/lab0/OExo01-Element/OExo01-Element.gen/sources_1/ip/ROM_D_1/ROM_D_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROM_D'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/Project/Vivado/lab0/OExo01-Element/OExo01-Element.srcs/sources_1/ip/ROM_D_1/ROM_D.xci
# IP: The module: 'ROM_D' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Project/Vivado/lab0/OExo01-Element/OExo01-Element.gen/sources_1/ip/ROM_D_1/ROM_D_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROM_D'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
