# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/muxctrl.xdc

# IP: ip/MUX4T1_5_0/MUX4T1_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MUX4T1_5_0 || ORIG_REF_NAME==MUX4T1_5_0} -quiet] -quiet

# IP: ip/MUX2T1_5_0/MUX2T1_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MUX2T1_5_0 || ORIG_REF_NAME==MUX2T1_5_0} -quiet] -quiet
